name: brakeman

on:
  - push
  - pull_request_target

jobs:
  brakeman:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: install dependencies
        run: |
          bundle install

      - name: brakeman
        run: bundle exec brakeman
